USE [master]
GO

/****** Object:  Database [PosFastFoods]    Script Date: 20/10/2024 8:54:22 CH ******/
CREATE DATABASE [PosFastFoods]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PosFastFoods', FILENAME = N'D:\APP\SQL\MSSQL16.SQLEXPRESS\MSSQL\DATA\PosFastFoods.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PosFastFoods_log', FILENAME = N'D:\APP\SQL\MSSQL16.SQLEXPRESS\MSSQL\DATA\PosFastFoods_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PosFastFoods].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PosFastFoods] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PosFastFoods] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PosFastFoods] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PosFastFoods] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PosFastFoods] SET ARITHABORT OFF 
GO

ALTER DATABASE [PosFastFoods] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PosFastFoods] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PosFastFoods] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PosFastFoods] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PosFastFoods] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PosFastFoods] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PosFastFoods] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PosFastFoods] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PosFastFoods] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PosFastFoods] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PosFastFoods] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PosFastFoods] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PosFastFoods] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PosFastFoods] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PosFastFoods] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PosFastFoods] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PosFastFoods] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PosFastFoods] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PosFastFoods] SET  MULTI_USER 
GO

ALTER DATABASE [PosFastFoods] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PosFastFoods] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PosFastFoods] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PosFastFoods] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PosFastFoods] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PosFastFoods] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PosFastFoods] SET QUERY_STORE = ON
GO

ALTER DATABASE [PosFastFoods] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PosFastFoods] SET  READ_WRITE 
GO


